blank_issues_enabled: false
contact_links:
  - name: ğŸ™ Question or Help
    url: https://github.com/vuejs/rfcs/discussions/new
    about: If you have a question or need help, ask a question on the discussion forums.
